name: InfiniteHunger
main: com.infamousdiamond.InfiniteHunger.InfiniteHunger
# Version is done like this, Major.Feature Added.Minor.Revision
version: 1.1.0.3
author: fishchunks
website: http://www.thecodearchive.com/
commands:
    IH:
        description: Shows information on InfiniteHunger
permissions:
  IH.IH:
    description: Lets you have infite hunger.
    default: op
